### PR TITLE
Fix couple of errors

### PR DESCRIPTION
**Pull request by alexsanjoseph**
- The API doesn't give correct value with Title case 
- The fact that you need to add @ts-nocheck is not explained in the text

### CODE REVIEW

**Comment by alexsanjoseph** [comment]
The second commit might be out of syllabus, feel free to tell me if I should revert

**Comment by mattcroat** [comment]
Thank you! 😄

I would like to accept the Pokemon API change but the decorators section is meant to be untyped because it's not the focus and I fear it's going to be more confusing to the reader while not being properly typed.

Can you remove that?

**Comment by alexsanjoseph** [comment]
Makes sense, I've removed the advanced typing part. I think it make sense to still kept the `ts-nocheck` part because else the example doesn't work (confused me when I was following your code from the text) and it is consistent with what you do in the video as well.

Is this better?

**Comment by alexsanjoseph** [comment]
Oh cool, didn't realize this was a way out! - Definitely better! Now there is a slight inconsistency between your video tutorial and this, but I don't think it should cause any confusion. LGTM!

**Comment by mattcroat** [comment]
Thank you! 😄

**Pull request merged**
